### ISSUE TITLE
which distribution is used in the pretrain phase?

### ISSUE THREAD

**Issue by connection-on-fiber-bundles** [deepmind/ferminet#14]
As mentioned in the Ferminet paper, the probability distribution used in the pretrain phase is the average between the HF one and the output from Ferminet output.
<img width="437" alt="Screen Shot 2021-01-26 at 3 01 01 PM" src="https://user-images.githubusercontent.com/35161116/105811278-58fd2000-5fe7-11eb-979d-23078a595969.png">

However, the implementation here seems doing something different:

In the master branch, even though we concat the walkers from both HF and Ferminet, but it seems only the ones from HF are used. 

<img width="709" alt="Screen Shot 2021-01-26 at 3 05 07 PM" src="https://user-images.githubusercontent.com/35161116/105811836-2e5f9700-5fe8-11eb-9fd2-d3f745639d85.png">

(My understanding is that in the [pretrain_hartree_fork](https://github.com/deepmind/ferminet/blob/master/ferminet/networks.py#L1255) function, only the first `tf.distribute.get_replica_context(). num_replicas_in_sync` walkers are used, which are basically the ones from HF).

On the other hand, in the JAX branch, it seems to me we are only using the ferminet output as the probability distribution when doing the pretrain. (Sorry I'm not that familiar with JAX. It's just that I can't find anything related to HF distribution around the pretrain code)

Is my understanding correct? Or does it mean the distribution used in pretrain is not that critical? Thanks!

**Comment by jsspencer** [comment]
Nice spot. Sorry, this is a bug in the TF code introduced when porting parallelisation over multiple GPUs from [TF-Replicator](https://arxiv.org/abs/1902.00465v1) to Distribution Strategy. The results in the FermiNet paper used TF-Replicator, which has a slightly different API to Distribution Strategy. With TF-Replicator, we are using the concatenated distribution on each GPU. The line you highlighted should read

```
concat_data = tf.concat([self.hf_data_gen.walkers, self.data_gen.walkers], axis=1)
```


We made a couple of different design decisions in the JAX version. We are currently only using the FermiNet as the distribution in pretraining. I think the pretraining distribution is not super critical -- the most important thing is to train the network such that it's closer to the ground state wavefunction and that the determinants aren't extremely low rank. Without pretraining, the network can start with an energy in the 1000s of hartrees (positive!) and optimising the network through that energy landscape is ... let's say painful. Certainly we don't see any noticeable difference in training FermiNet after pretraining in the TF or JAX codes.

**Comment by connection-on-fiber-bundles** [comment]
Got it. Thanks a lot for the detailed explanation!

**Comment by jsspencer** [comment]
Whilst we don't believe this makes a significant difference, the TF version on master is now updated to sample from both distributions during pretraining.
