### ISSUE TITLE
Issues (or typos?) when running JAX code with multiple GPUs

### ISSUE THREAD

**Issue by connection-on-fiber-bundles** [deepmind/ferminet#16]
Hi there. Got two issues when running the JAX code with multiple GPUs:

1. https://github.com/deepmind/ferminet/blob/b46077f1a4687b3ac03b583d9726f59ab4d914d9/ferminet/train.py#L293-L297
It would hit `too many values to unpack` error when `num_devices` is greater than 1.
My understanding is that we should do
```
key, *subkeys = jax.random.split(key, num_devices+1)
```
instead (note the extra asterisk), in which case the following explicit broadcast is not necessary any more for single GPU case.

2. https://github.com/deepmind/ferminet/blob/b46077f1a4687b3ac03b583d9726f59ab4d914d9/ferminet/train.py#L372-L373
`constants.pmap` gives a tuple of an array instead of just an array in this case when `num_devices` is greater than 1 (not sure why, probably just JAX's API). This would cause logging to complain. It's easy to fix though.

Let me know if it makes sense. Also if you like, I can submit a tiny PR to fix them

**Comment by dpfau** [comment]
That does make sense - might be just a small change from the internal version that we never tested. We'd be happy to look at a PR.

**Comment by jsspencer** [comment]
Sorry, these crept in when removing a small internal dependency and as a typo respectively. Happy to take a look at a PR, equally happy to release an updated version early next week with fixes.

**Comment by connection-on-fiber-bundles** [comment]
Got it. Will work on a fix PR then

**Comment by connection-on-fiber-bundles** [comment]
By the way, for case 2 (the logging one)，I got confused by the error message. It should be the case that `constants.pmap` always returns an array (of the same values in this case) whose size is equal to `num_devices`. It's just that when the array is of size 1, then logging can handle it automatically while if the size the greater than 1, it would complain. So I simply take the first element her in my PR.

**Comment by jsspencer** [comment]
That's the correct thing to do. `pmean` is a collective reduce (ie like MPI_AllReduce instead of MPI_Reduce, if you're familiar with MPI) and the result is sharded all devices. The logging call requires the data on the host, which transfers the array back, resulting in an array of length `num_devices`, with elements, as you say, indentical due to the `pmean`. The same thing is done in several places during the main training loop.

**Comment by jsspencer** [comment]
Fixed in #17. Thanks for spotting this and sending the patch!
