### ISSUE TITLE
Variance of a converged model

### ISSUE THREAD

**Issue by n-gao** [deepmind/ferminet#29]
Good day,

I played around with the ferminet implementation a bit and noticed that for small systems like H2 the network very quickly converges with a low variance on the local energy. Though, for the Hydrogen chain with 10 atoms I noticed the variance to converge significantly slower. Could you please share the variance of the converged models for the Hydrogan chain in the original FermiNet paper for reference?

Thanks!

**Comment by dpfau** [comment]
That sounds right. We can get H2 nearly perfectly, so we'd expect the
variance to be near zero. H10 isn't quite as accurate, so we'd expect the
variance to be higher. We don't have published numbers for the variance, I
believe, but the logging provided here (
https://github.com/deepmind/ferminet/blob/jax/ferminet/train.py#L533)
should give you all you need. This is the same code that we run, so it
should give you the same answers as us.

**Comment by n-gao** [comment]
Thanks for the quick response! Could you give an order of magnitude for the variance, as running the experiment is quite costly on GPU time? 10^-3, 10^-4, ...?

**Comment by jsspencer** [comment]
Note that the variance logged is just the variance over the batch. This is sometimes (but rarely) a useful diagnostic and is extremely noisy, especially for relatively small batch sizes and large systems (your H2 calculation is probably in the opposite regime, with a comparatively large batch size for a small system).

From the logged output, you can calculate the mean and variance of the local energy quite easily. In both cases, serial correlation needs to be removed. The CASINO manual is (as ever) excellent on such technical details.

**Comment by jsspencer** [comment]
For a ballpark estimate, our papers report a typical standard error of O(10^{-5}) Ha from O(10^5) Metropolis-Hastings steps. The correlation time is not reported but it's usually not large for VMC. Either way, this gives an upper bound on the variance of these calculations.

**Comment by n-gao** [comment]
Thanks for the estimate and insights. Does O(10^5) Metropolis-Hastings steps refer to the number of actual steps, the number of samples or the number of batches since these all differ by orders of magnitude?

**Comment by jsspencer** [comment]
The calculations in our papers typically used 10^4-10^5 energy evaluations (averaged over the batch of walkers, usually of O(2^12)), with O(10) Metropolis-Hastings steps between each energy evaluation. The standard error was calculated from the set of energy evaluations.

**Comment by n-gao** [comment]
Thanks for the details!
