### ISSUE TITLE
install eeror

### ISSUE THREAD

**Issue by KingDamLiu** [deepmind/ferminet#36]
(plm) (ferminet) [liujinde@node02 ferminet-master]$ python -m pytest
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.7.3, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /home/liujinde/Dowload/ferminet-master
collected 135 items                                                                                                                                                        

ferminet/tests/hamiltonian_test.py ..s..s..s...s                                                                                                                     [  9%]
ferminet/tests/mcmc_test.py ...s                                                                                                                                     [ 12%]
ferminet/tests/networks_test.py ...Fatal Python error: Fatal Python error: Fatal Python error: Fatal Python error: Fatal Python error: Fatal Python error: Fatal Python error: Fatal Python error: Segmentation faultSegmentation faultSegmentation faultSegmentation faultSegmentation faultSegmentation faultSegmentation fault

Segmentation fault (core dumped)

**Comment by jsspencer** [comment]
This is too little information to try to reproduce. Is this with the TF or JAX implementation?

Either way, I suspect the issue is with your TF or JAX installation. Can you check that their tests pass, especially on GPU if you're using a GPU.

**Comment by KingDamLiu** [comment]
thanks!The problem is be solved!It's because that the version of pyscf package eeror!I installed 2.0 but it's need <2.0.

**Comment by jsspencer** [comment]
So it is -- I think you're hitting https://github.com/pyscf/pyscf/issues/1095. I can reproduce this (the failing tests are all in `train_test.py`) once I upgraded pyscf to 2.0, with pyscf installed from PyPI. Using a previous version of pyscf or compiling pyscf from source worked for me.
