### ISSUE TITLE
Jax install - issue with correct version number

### ISSUE THREAD

**Issue by Dehavendrew** [deepmind/ferminet#43]
Hi,

Apologies for the basic question, but I am having issue running the test scripts provided and I believe it is an issue with the version of Jax that was installed by default within the Setup script. Below are the versions that were automatically installed:

![image](https://user-images.githubusercontent.com/43423063/160321631-55ca3539-96ed-4b74-a1ce-8d04c3ee4851.png)

And here is the error message that is causing each test to fail.

![image](https://user-images.githubusercontent.com/43423063/160321704-e9db87af-f61e-440d-92e5-ad473dd1bc3f.png)

Currently I am running this off the main branch within a Google Colab notebook with GPU backend enabled.

What version of Jax/Jaxlib should I be using?

Thank you for the help!

**Comment by jsspencer** [comment]
Sorry, there's apparently an API change we hadn't picked up on. This is used deeply inside KFAC and fixing it will take some time.

In the meantime, jax 0.2.21 and jaxlib 0.17.5 work fine for me (at least on a CPU backend).
