### ISSUE TITLE
Different results obtained from the paper for ch3nh2

### ISSUE THREAD

**Issue by lamthuy** [deepmind/ferminet#68]
Hi,
I run ferminet for ch3nh2 with the coordinates of the atom provided in the appendix of the Ferminet paper. The energy is around -91.5 Eh instead of -95.51 Eh. 
I guess that might be due to the unit of the coordinates of the atoms provided in the appendix is not Bohr? 
In the Appendix I saw provided coordinates of o3, c4h6, c2h4 etc, are they in Bohr or Angstrom? In the paper I cannot find the information about the units of those structures. 

Below is the input configs for ch3nh2:
``` python
from ferminet import base_config
from ferminet.utils import system
import ml_collections


def get_config() -> ml_collections.ConfigDict:
  """Returns config for running CH3NH2 with FermiNet."""
  cfg = base_config.default()
  # geometry in bohr.
  cfg.system.molecule = [
      system.Atom(symbol='C', coords=(0.0517, 0.7044, 0.0)),
      system.Atom(symbol='N', coords=(0.0517, -0.7596, 0.0)),
      system.Atom(symbol='H', coords=(-0.9417, 1.1762, 0.0)),
      system.Atom(symbol='H', coords=(-0.4582, -1.0994, 0.8124)),
      system.Atom(symbol='H', coords=(-0.4582, -1.0994, -0.8124)),
      system.Atom(symbol='H', coords=(0.5928, 1.0567, 0.8807)),
      system.Atom(symbol='H', coords=(0.5928, 1.0567, -0.8807)),
  ]
  cfg.system.electrons = (9, 9)
  return cfg
```

**Comment by jsspencer** [comment]
The header for the positions column in each table in Appendix G gives the units as bohr. Unfortunately there was an oversight in preparing Table X (methylamine) and the coordinates for that molecule are actually in Angstroms. Sorry for this. [You can also check the G3 dataset and/or run Hartree-Fock on the structures and compare to thse in Table II.]

I have checked that the other systems are correctly given in Bohr. There is one other small error - for ethanol, the position of the last hydrogen was cut off. Its full structure is:

```
C 2.20754 -0.7566 0.0000
C 0.00000 1.0572 0.0000
O -2.24893 -0.4302 0.0000
H -3.67858 0.7210 0.0000
H 0.08042 2.2819 1.6761
H 0.08042 2.2819 -1.6761
H 3.99845 0.2736 0.0000
H 2.13274 -1.9601 1.6741
H 2.13274 -1.9601 -1.6741
```

**Comment by lamthuy** [comment]
That is a great help, I also noticed missing coordinate for an Hydrogen for Ethanol. I don't know where is the right link to access to the g3 database. I found the paper but could not find the link to the database.
