### ISSUE TITLE
Questions about the convergence

### ISSUE THREAD

**Issue by ley61** [deepmind/ferminet#7]
Hi, there~ Thanks to your kind guidance, I have successfully run ferminet program  and get some results about, for example, H4 circle. However the output energy for each iteration still has oscillating behavior roughly about 0.1 Eh even after 10^5 iterations. 

So I just want to ask how can I know this network has been well trained?  I mean when can I stop updating the network parameters and use it to calculate energy accurately?

I note the default iteration in your program is 10^6, and I wonder whether this oscillating behavior will be cured at that time.

**Comment by dpfau** [comment]
Is this in JAX or TF? Which optimizer - KFAC or ADAM? With KFAC (only available in TF) you'd expect it to be pretty well converged by 10^5. I'm less sure about the behavior with ADAM.

**Comment by jsspencer** [comment]
Please provide full details of your calculation configuration, including the batch size. It is impossible to know what variance to expect without this information. Have you used any Monte Carlo algorithms before? You will need to average the energy over multiple iterations (we typically use 10k-50k) to get a good energy estimate. During training, a rolling mean is also helpful to check convergence.

For H4 you can compare to FCI calculations (and extrapolate them to the complete basis set limit) to get a good ground truth estimate.

**Comment by ley61** [comment]
Myflag is "--system_type h4_circle --system_separation 3.2843 --system_angle 0.7853981633974483 --batch_size 1024 --iterations 100000 --multi_gpu" , and it's in Tf with Kfac optimizer. 

I think my previous claim 0.1 Eh is wrong. The result for H4 is around about -2.013~-2.015Eh actually after 10^5 steps. But I think this accuracy is still not enough to determine the stable angle for H4 circle.

**Comment by ley61** [comment]
Ok, I think I know what should I do: using bigger batch_size, take the mean energy of the last several steps to judge the convergence. Then I can stop training and  average the energy over multiple iterations just like you adviced 10k-50k.

**Comment by jsspencer** [comment]
Fluctuations in the energy from a single batch of that range for H4 are entirely normal (c.f. Fig 3 in our paper). Averaging this over 10k-50k iterations (without parameter updates) will give an excellent estimate of the energy. Remember to use a method to remove the autocorrelation to give a good estimate of the standard error in the energy (e.g. blocking, as we did).

Even noisy estimates can give very good energies over a long period. Given a fixed function, the estimate from averaging the energy of a batch of size 1 over N steps is equivalent to averaging over a batch of size N over 1 step!
