### ISSUE TITLE
JAX implementation of the derivatives of log determinents

### ISSUE THREAD

**Issue by connection-on-fiber-bundles** [deepmind/ferminet#8]
To my knowledge, the sonnet implementation (master branch) used a hand-rolled gradient function for the `logdet_matmul` function corresponding to the Appendix C of the Ferminet paper. However, in the JAX implemention, such hand-rolled gradient function seems gone. 

Could someone shed some light on the rationale behind the change? Is it because JAX is doing something smarter when differentiating a slogdet function? Thanks!

**Comment by dpfau** [comment]
Very good eye. We found empirically that there is some subtle difference in how slogdet is implemented in JAX versus TF, such that the failures of TF training that we saw simply didn't happen in JAX. The numerical results in JAX also seem slightly better than in TF (for instance, the absolute energy of bicyclobutane is ~8 mHa lower) so we are not too concerned about the discrepancy going forward.
