### ISSUE TITLE
Error in set-up 

### ISSUE THREAD

**Issue by ph7klw76** [deepmind/ferminet#9]
when i run the setup of ferminet, I got an error below:

File "C:\Users\user\anaconda3\envs\FermiNet\lib\site-packages\setuptools\package_index.py", line 119, in distros_for_location
    wheel = Wheel(basename)
  File "C:\Users\user\anaconda3\envs\FermiNet\lib\site-packages\setuptools\wheel.py", line 61, in __init__
    raise ValueError('invalid wheel name: %r' % filename)
ValueError: invalid wheel name: 'pyscf-1.4.3-cp34-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl'

I am using anaconda in window 64 bits to setup using terminal

**Comment by jsspencer** [comment]
I'm sorry, but I'm not familiar with Windows and don't have a Windows machine to test. I also do not use anaconda. It looks like something is going wrong with installing the pyscf dependency, so I suggest you focus on installing that separately first inside the same environment. Once you have installed pyscf, then proceed to installing ferminet. The pyscf documentation contains installation instructions: https://sunqm.github.io/pyscf/install.html

Some general observations:

1. Despite being on Windows, anaconda is attempting to find a Mac OSX wheel for pyscf.
2. The pyscf version installed (1.4.3) is some years old (1.7 is now available).

This points to a problem with your anaconda setup...

**Comment by ph7klw76** [comment]
Thanks, problems solved by transporting to a Linux system. Still need to install pyscf before installing ferminet
